### PR TITLE
LEB-11 add base code for leforwork whitelabel

### PR DESCRIPTION
**Pull request by MatthewDelaneyAtLuxuryEscapes**
Braintree is paypal according to @eddiemcleanlux

### CODE REVIEW

**Review by tracymu — COMMENTED** [review]
Cool - I don't know about the settings, maybe that's what you're going to be asking AJ about.

Also you'll need to update this package

and maybe tests

**Comment by MatthewDelaneyAtLuxuryEscapes** [comment]
> Cool - I don't know about the settings, maybe that's what you're going to be asking AJ about.
> 
> Also you'll need to update this package
> 
> and maybe tests

yeap, that's what I'm going to be asking AJ abou

**Comment by tracymu** [comment]
why did you undo the package bump?

**Comment by MatthewDelaneyAtLuxuryEscapes** [comment]
> why did you undo the package bump?

the readme has a recommended way of updating this package

**Review by tracymu — APPROVED** [review]

**Pull request merged**
