### PR TITLE
fix(local phone numbers) Set default phone numbers to local

### PR DESCRIPTION
**Pull request by Sonyque**
## Description
Set default phone numbers to local where they exist

If local phone numbers exist, we should show them instead of the international variant..

### CODE REVIEW

**Comment by marhalpert** [comment]
you need ti bump the version

**Comment by Sonyque** [comment]
@marhalpert cccording to the readme I need to do it in a separate PR https://github.com/lux-group/lib-regions/blob/ab6a3b11ce8d5251d9ea31e8ecea0bd38c75c5b1/README.md?plain=1#L13-L18

**Comment by marhalpert** [comment]
> @marhalpert cccording to the readme I need to do it in a separate PR
> 
> https://github.com/lux-group/lib-regions/blob/ab6a3b11ce8d5251d9ea31e8ecea0bd38c75c5b1/README.md?plain=1#L13-L18

I wonder why? it is not a technical restriction https://github.com/lux-group/lib-regions/pull/310/files

**Comment by marhalpert** [comment]
I think the readme is outdated, the release happens in CI now

**Review by dyachoksa — APPROVED** [review]

**Pull request merged**
