### PR TITLE
Noissue add nwl regions

### PR DESCRIPTION
**Pull request by mikedao-le**
Adding a new white label brand.

Tested locally by setting up:
- svc-offer
- svc-public-offer
- www-le-customer

It is probably used in other places, too - not sure yet.

### CODE REVIEW

**Comment by nizhu** [comment]
would it be prudent to limit the regions and payment methods. i doubt we're going to create all the accounts necessary for all the combinations in the spike anyway.

**Comment by nizhu** [comment]
i'd even just run everything off the branches

**Comment by mikedao-le** [comment]
> would it be prudent to limit the regions and payment methods. i doubt we're going to create all the accounts necessary for all the combinations in the spike anyway.

👍  I'd can limit to AU , but I'd like all payment methods, because I was told the goal of this project is to later improve and white labelling feature and that will probably involve figuring out combinations in which the branding works / doesn't work.

**Comment by mikedao-le** [comment]
> i'd even just run everything off the branches

What do you mean? 🤔  Like install the lib off the branch?

**Review by nizhu — APPROVED** [review]

**Pull request merged**
