### PR TITLE
[TBB-227]: Update the Indian support number

### PR DESCRIPTION
**Pull request by marhalpert**
This PR updates the Indian support number

### CODE REVIEW

**Comment by zediah** [comment]
You've more than re-installed deps, you've updated them 😱

**Review by zediah — APPROVED** [review]
I imagine the NPM updates should be fine, lib-regions doesn't do much really...

**Comment by keithbro** [comment]
> I imagine the NPM updates should be fine, lib-regions doesn't do much really...

Also bear in mind, the yarn.lock has no effect on what gets installed when this library is installed in to an application. Only the versions in package.json matter for libraries. That's why often its best not to check in yarn.lock for libraries.

**Comment by marhalpert** [comment]
> You've more than re-installed deps, you've updated them 😱

Will do it as part of ENGEX.. I don't have time to properly test it now.. reverted back yarn.lock file

**Comment by zediah** [comment]
> > I imagine the NPM updates should be fine, lib-regions doesn't do much really...
> 
> Also bear in mind, the yarn.lock has no effect on what gets installed when this library is installed in to an application. Only the versions in package.json matter for libraries. That's why often its best not to check in yarn.lock for libraries.

😱 good point and that's scary then. Should definitely pin library requirements right?

**Comment by keithbro** [comment]
> > > I imagine the NPM updates should be fine, lib-regions doesn't do much really...
> > 
> > 
> > Also bear in mind, the yarn.lock has no effect on what gets installed when this library is installed in to an application. Only the versions in package.json matter for libraries. That's why often its best not to check in yarn.lock for libraries.
> 
> 😱 good point and that's scary then. Should definitely pin library requirements right?

you could take that approach. personally i'd prefer to let tests in the lib and in the app catch regressions, and stay using the latest versions where possible

**Pull request merged**
